name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add Hugging Face remote with token
        env:
          HF: ${{ secrets.HF }}
        run: |
          git remote remove space || true  # Remove if already exists
          git remote add space https://${HF}@huggingface.co/spaces/Tanzila21/mlops

      - name: Push to Hugging Face space
        run: git push --force space main

